version: '3.9'

services:
  nginx:
    build:
      context: ./nginx
    image: local-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.confi
    networks:
      - nginx-network

  python-app:
    build:
      context: ./Python
    image: local-python-app
    container_name: python_app
    expose:
      - "8000"
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge